# Expected LDP Peer Configuration
# Format: device_name: [{peer_id: router_id, expected_state: state}]

# Core Routers
core-router-1:
  - peer_id: '2.2.2.2'  # core-router-2
    expected_state: 'operational'
  - peer_id: '3.3.3.3'  # edge-router-1
    expected_state: 'operational'
  - peer_id: '5.5.5.5'  # distribution-router-1
    expected_state: 'operational'

core-router-2:
  - peer_id: '1.1.1.1'  # core-router-1
    expected_state: 'operational'
  - peer_id: '4.4.4.4'  # edge-router-2
    expected_state: 'operational'
  - peer_id: '6.6.6.6'  # distribution-router-2
    expected_state: 'operational'

# Edge Routers
edge-router-1:
  - peer_id: '1.1.1.1'  # core-router-1
    expected_state: 'operational'
  - peer_id: '5.5.5.5'  # distribution-router-1
    expected_state: 'operational'

edge-router-2:
  - peer_id: '2.2.2.2'  # core-router-2
    expected_state: 'operational'
  - peer_id: '6.6.6.6'  # distribution-router-2
    expected_state: 'operational'

# Distribution Routers
distribution-router-1:
  - peer_id: '1.1.1.1'  # core-router-1
    expected_state: 'operational'
  - peer_id: '3.3.3.3'  # edge-router-1
    expected_state: 'operational'

distribution-router-2:
  - peer_id: '2.2.2.2'  # core-router-2 
    expected_state: 'operational'
  - peer_id: '4.4.4.4'  # edge-router-2
    expected_state: 'operational'
