# Expected BGP Peer Configuration
# Format: device_name: {peer_ip: {peer_as: AS_number, expected_state: state}}

# Core Routers
core-router-1:
  10.1.1.2:
    peer_as: '65002'
    expected_state: 'established'
  10.1.2.2:
    peer_as: '65003'
    expected_state: 'established'
  192.168.100.1:
    peer_as: '65100'
    expected_state: 'established'

core-router-2:
  10.1.1.1:
    peer_as: '65001'
    expected_state: 'established'
  10.2.1.2:
    peer_as: '65004'
    expected_state: 'established'
  192.168.100.2:
    peer_as: '65100'
    expected_state: 'established'

# Edge Routers
edge-router-1:
  10.1.2.1:
    peer_as: '65001'
    expected_state: 'established'
  172.16.1.2:
    peer_as: '65200'
    expected_state: 'established'

edge-router-2:
  10.2.1.1:
    peer_as: '65002'
    expected_state: 'established'
  172.16.2.2:
    peer_as: '65300'
    expected_state: 'established'

# Internet Edge
inet-edge:
  192.168.100.1:
    peer_as: '65001'
    expected_state: 'established'
  192.168.100.2:
    peer_as: '65002'
    expected_state: 'established'
  203.0.113.1:
    peer_as: '64496'
    expected_state: 'established'
  203.0.113.5:
    peer_as: '64497'
    expected_state: 'established'
