# Expected OSPF Neighbor Configuration
# Format: device_name: {process_id: expected_count}

# Core Routers
core-router-1:
  '1': 4  # Process 1 should have 4 neighbors
  '10': 2 # Process 10 should have 2 neighbors (management)

core-router-2:
  '1': 4
  '10': 2

# Edge Routers
edge-router-1:
  '1': 3
  '10': 1

edge-router-2:
  '1': 3
  '10': 1

# Distribution Routers
distribution-router-1:
  '1': 3
  '10': 1

distribution-router-2:
  '1': 3
  '10': 1

# Access Routers
access-router-1:
  '1': 1
  '2': 1  # Local area OSPF process

access-router-2:
  '1': 1
  '2': 1

access-router-3:
  '1': 1
  '2': 2

access-router-4:
  '1': 1
  '2': 2

# Management Router
mgmt-router:
  '10': 6  # Connected to all core and management interfaces
